rules = [
  DisableSyntax
  OrganizeImports
]

DisableSyntax {
  noThrows = true
  noNulls = true
  noReturns = true
  noWhileLoops = true
  noAsInstanceOf = true
  noIsInstanceOf = true
  noFinalize = true
}

OrganizeImports {
  removeUnused = false
  targetDialect = Scala3
}
